In [2]:
# hi yek pyhton librery ahe jyat apn avirous mathematical caluctaion easy way madhe kru shkto smjl ka
# no need to write the functions for calculations mssj  ka
# to code ty function madhe adhi lilila asto
# function la call kra ani tyat  value takun solve kra questions mjlka

# main game numpy madhe array krto jo collection of rhe simpliar kind of data type asto jyat na bhava
# direct navlue takun game honar list peksha na to na 50 x fatse r asto smjl ka

# driect na ts nahi kru shkt so we used bro ! smjl ka bhava
! pip install numpy

In [5]:
#Q creation of the array
import numpy as np

# take the arrya and print it

arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [2]:
#create the array and display it smjl ka
# ha kay kela mi arrya create kela smjl ka
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr)

type(arr)

[ 10  20  30  40  50  60  70  80  90 100]


numpy.ndarray

In [3]:
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarra
#nd array madhe na apan na bhava tuple and ajun list and barch kahi atku shkto smjl ka
# Q use the tuple and create the numpy array smjl ka

brr = np.array((10,20,30,40,50,60,70,80,90,100))
print(brr)

[ 10  20  30  40  50  60  70  80  90 100]


In [7]:
# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
# 0 d array mnje tyat na yekch value aste smjl ka
#Q Create a 0-D array with value 42
arr3 = np.array([42])
print(arr3)
type(arr3)

[42]


numpy.ndarray

In [6]:
arr4 = np.array(42)

print(arr4)
type(arr4)

42


numpy.ndarray

In [8]:
# 1-D Arrays
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

# These are the most common and basic arrays.
#Q Create a 1-D array containing the values 1,2,3,4,5:

arr5 = np.array([1,2,3,4,5])
print(arr5)

[1 2 3 4 5]


In [11]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.

# These are often used to represent matrix or 2nd order tensors.

#Qreate a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

#arr6 = np.array([1,2,3],[4,5,6])  # wrong
#arr6 = np.array([1,2,3],[4,5])   #Wrong
arr6 = np.array([[1,2,3],[4,5,6]])

print(arr6)

[[1 2 3]
 [4 5 6]]


In [12]:
# 3-D arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

# These are often used to represent a 3rd order tensor.

# Q Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

arr7 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr7)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [17]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.

# When the array is created, you can define the number of dimensions by using the ndmin argument.

#Q Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [18]:
#Topic 2 :: NumPy Array Indexing
# Access Array Elements
# Array indexing is the same as accessing an array element.

# You can access an array element by referring to its index number.

# The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

#Q Get the first element from the following array:

arr8 = np.array([10,20,30,40,50])
print(arr8[0])






10


In [19]:
#Q Get the second element from the following array.

arr9 = np.array([1, 2, 3, 4])

print(arr9[1])

2


In [21]:
# Q Get third and fourth elements from the following array and add them.

arr10 = np.array([1, 2, 3, 4])
print(arr10[2]+ arr10[3])


7


In [24]:
# # Access 2-D Arrays
# To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

# Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

arr10 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr10[0,0])
print(arr10[0,1])
print(arr10[1,0])


1
2
6


In [25]:
#Q Access the element on the 2nd row, 5th column:

arr11 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr11[1,4])


10


In [27]:
# Access 3-D Arrays
# To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

#Q Access the third element of the second array of the first array:
arr12= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

#print(arr12[2,1,0])  # chukiych ye vadvat jaych smjl ka

print(arr12[0,1,2])

6


In [30]:
#Negative Indexing
#Use negative indexing to access an array from the end.

#Q Print the last element from the 2nd dim:

arr13 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr13[0,-1])
print(arr13[1,-1])   # correct ans
print(arr13[-1,-1])   # dont know jau de forgot this ok

5
10
10


In [ ]:
# # topic 3 NumPy Array Slicing

# Slicing arrays
# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].

# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0

# If we don't pass end its considered length of array in that dimension

# If we don't pass step its considered 1



In [31]:
#Q Slice elements from index 1 to index 5 from the following array:

arr14 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr14[1:5])

[2 3 4 5]


In [ ]:
# Note: The result includes the start index, but excludes the end index.

In [35]:
# Q Slice elements from index 4 to the end of the array:
arr15 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr15[4:6])   # wrong ye smjl ka slice madhe len + 1 yenar smjl kalast element
print(arr15[4:7])

#or
print(arr15[4:])

[5 6]
[5 6 7]
[5 6 7]


In [36]:
#Slice elements from the beginning to index 4 (not included):
arr16 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr16[:4])

[1 2 3 4]


In [37]:
# Negative Slicing
# Use the minus operator to refer to an index from the end:

#Slice from the index 3 from the end to index 1 from the end:
arr17 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr17[-4:-1])

print(arr17[-3:-1])   # correct ans

[4 5 6]


In [38]:
# STEP
# Use the step value to determine the step of the slicing:
#Return every other element from index 1 to index 5:
# Q other elemnt mnjebhava 1 soudn asto smjl ka
arr18 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr18[1:5:2])



[2 4]


In [40]:
# Q Return every other element from the entire array:

print(arr18[0::2])
print(arr18[::2])

[1 3 5 7]
[1 3 5 7]


In [41]:
#Slicing 2-D Arrays

#From the second element, slice elements from index 1 to index 4 (not included):
arr19 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr19[1,1:4])

[7 8 9]


In [42]:
#From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


In [43]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
# #NumPy Data Types
# By default Python have these data types:

# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

In [ ]:
# Data Types in NumPy
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

# Below is a list of all data types in NumPy and the characters used to represent them.

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )


In [44]:
# Checking the Data Type of an Array
# The NumPy array object has a property called dtype that returns the data type of the array:

# ExampleGet your own Python Server
# Get the data type of an array object:

# import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [45]:
# Get the data type of an array containing strings:


arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [49]:
# Creating Arrays With a Defined Data Type
# We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

#Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype= str)
arr = np.array([1, 2, 3, 4], dtype= 'S')

print(arr)
print(arr.dtype)


# For i, u, f, S and U we can define size as well.

[b'1' b'2' b'3' b'4']
|S1


In [50]:
#Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)
print(type(arr))


[1 2 3 4]
int32
<class 'numpy.ndarray'>


In [ ]:
# # numpy array copy vs view
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

# The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [51]:
# Make a copy, change the original array, and display both arrays:

# import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [52]:
# Make a view, change the original array, and display both arrays:

# import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [53]:
# Make a view, change the view, and display both arrays:

# import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [54]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [55]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
# Reshape From 1-D to 3-D
# Example
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

# import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [57]:
# Can We Reshape Into any Shape?
# Yes, as long as the elements required for reshaping are equal in both shapes.

# We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
# Example
# Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

# import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)


ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:

# Flattening the arrays
# Flattening array means converting a multidimensional array into a 1D array.

# We can use reshape(-1) to do this.

# Example
# Convert the array into a 1D array:

# import numpy as np

# arr = np.array([[1, 2, 3], [4, 5, 6]])

# newarr = arr.reshape(-1)

# Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.