# Numpy
NumPy is a popular Python library for numerical and scientific computing
Importing NumPy


In [11]:
import numpy as np

NumPy Arrays
Numpy arrays can be created from lists, tuples, or other iterable objects.


In [12]:
# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

arr_1d

array([1, 2, 3, 4, 5])

In [13]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:


# Creating arrays with specific values
zeros = np.zeros((2, 3))  # Array of zeros
print(zeros)

ones = np.ones((3, 4))  # Array of ones
print(ones)

identity = np.eye(3)  # Identity matrix
print(identity)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Array Operations
We can perform various operations on NumPy arrays, such as addition, subtraction, multiplication, and more.

In [15]:
a = [1,2,3]
b = [3,4,6]
print(a+b)

[1, 2, 3, 3, 4, 6]


In [16]:

# Array operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b


Indexing and Slicing:
We can access elements and slices of arrays using indexing.

In [17]:

# Indexing and slicing
arr = np.array([1, 2, 3, 4, 5])

element = arr[2]
slice = arr[1:4]
slice

array([2, 3, 4])

Array Shape and Size:
We can check the shape and size of an array.

In [18]:

# Shape and size
#shape = arr_2d.shape  # Shape of a 2D array
size = arr.size  # Total number of elements in an array
size

5

Reshaping Arrays:
We can change the shape of an array using the reshape method.

In [19]:
# Reshaping arrays
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(3, 2)
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

Statistical Operations:
NumPy provides various statistical functions for analyzing data.

In [20]:

# Statistical operations
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print(mean)
print(median)
print(std_dev)

3.5
3.5
1.707825127659933


Random Number Generation:
We can generate random numbers and arrays using NumPy.

In [21]:
import random
# Random number generation
random_int = np.random.randint(1000, 50000)  # Random integer between 1 and 100
random_int


1869

In [22]:
random_array = np.random.rand(3, 4)  # 3x4 array of random floats
random_array

array([[0.50964288, 0.00256877, 0.52569946, 0.19650913],
       [0.54355269, 0.09623561, 0.5985013 , 0.04933084],
       [0.08169708, 0.71704198, 0.89069566, 0.25682258]])

In [23]:
# Generate a random floating-point number
random_number = np.random.uniform(0, 1)
print(random_number)


random_value = np.random.uniform(10, 20)
print(random_value)

0.8713772022305736
11.68733143694803
